module.exports = {
  Modules: {
    General: ["modules/general/main", "modules/general/includes-conditionals"],
    Information: [
      "modules/information/tutorial",
      "modules/information/broadcasts",
      "modules/information/rules",
    ],
    Environment: [
      "modules/environment/world",
      "modules/environment/time",
      "modules/environment/border",
      "modules/environment/mobs",
    ],
    Format: ["modules/format/players", "modules/format/teams"],
    Objectives: [
      "modules/objectives/ctw",
      "modules/objectives/ctf",
      "modules/objectives/control-points",
      "modules/objectives/dtm",
      "modules/objectives/dtc",
      "modules/objectives/monument-modes",
      "modules/objectives/blitz",
      "modules/objectives/scoring",
      "modules/objectives/other",
    ],
    Mechanics: [
      "modules/mechanics/filters",
      "modules/mechanics/regions",
      "modules/mechanics/spawns",
      "modules/mechanics/portals",
      "modules/mechanics/proximity-alarms",
      "modules/mechanics/lanes",
      "modules/mechanics/damage",
      "modules/mechanics/gamerules",
    ],
    Gear: [
      "modules/gear/items",
      "modules/gear/potions",
      "modules/gear/kits",
      "modules/gear/classes",
      "modules/gear/pickups",
      "modules/gear/item-mods",
      "modules/gear/crafting",
      "modules/gear/repair-remove-keep",
      "modules/gear/projectiles",
      "modules/gear/tnt",
      "modules/gear/kill-rewards",
      "modules/gear/lootables",
    ],
  },
  Reference: {
    Items: ["reference/items/inventory"],
  },
  Guides: {
    "XML Pointers": ["guides/xml-pointers/regions"],
    Contribute: ["guides/contribute/migrate"],
  },
};
