name: PGM
api-version: 1.20.6
description: ${project.parent.description}
main: ${project.mainClass}
version: ${project.version} (git-${git.commit.id.abbrev})
website: ${project.parent.url}
bootstrapper: tc.oc.pgm.platform.modern.PgmBootstrap

dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: true
      join-classpath: true
    ViaVersion:
      load: BEFORE
      required: false
      join-classpath: true