name: ${project.parent.name}
description: ${project.parent.description}
main: ${project.pluginClass}
softdepend: ${project.pluginSoftDepedencies}
version: ${project.version}-${git.commit.id.abbrev}
website: ${project.parent.url}
author: ${project.author}
